version: "2.4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    pid: "host"
    environment:
      - TZ=Asia/Tehran
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_NAME=vafa
      - PG_USER=admin
      - PG_PASS=admin
      - LOG_LEVEL=debug
      - LOG_OUTPUT_TYPE=stdout
      - LOG_FILE_Add=/log.txt

    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres:alpine3.14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=vafa
    volumes:
      - ~/dockerv/postgres/:/var/lib/postgresql/data